name: Build
on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  deploy_cloudflare:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            # Get jq
            apt-get update -y && apt-get install -y jq

            # Install packages
            npm install

            # Create the namespace if it doesn't exist
            wrangler2 kv namespace list | grep -q apakr-files || wrangler2 kv:namespace create apakr-files

            # Get the namespace ID
            namespaceid=$(wrangler2 kv namespace list | jq '.[] | select(.title=="apakr-apakr-files") | .id')

            # Add the binding to the wrangler.toml
            echo "kv_namespaces = [ { binding = 'ApakrFiles', id = $namespaceid } ]" >> wrangler.toml
  deploy_deno:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          entrypoint: "src/deno.ts"
          root: "."